# config1.yaml
nodeId: "futterküche"
listenAddr: ":7777"
iperfPort: 5201
knownPeers:
  - "localhost:7778"
  - "localhost:7779"
dataFile: "node1_data.json"
testConfig:
  iperfInterval: 30
  mLabInterval: 300
  targetBandwidth: "1Gbps"