nodeId: "kassenhaus"
nodeIPPort: "127.0.0.1:8082"
nodeHttpPort: "8082"
listenAddr: ":7778"
iperfPort: 5202
knownPeers:
  - "localhost:7777"
  - "localhost:7779"
dataFile: "node2_data.json"
testConfig:
  iperfInterval: 30
  mLabInterval: 300
  targetBandwidth: "1Gbps"